# Generated by Django 5.0.4 on 2024-05-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='title',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
